<?php
/**
 * THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
 * For more information, see http://github.com/elliotboney/
 *
 * Generated on: 04/09/2014 @ 15:12:34
 *
 * MIT License
 * ===========
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * @category  Services
 * @package   AffiliateProgramService
 * @author    Elliot Boney <elliotboney@gmail.com>
 * @copyright 1997-2013 Digital Grove, LLC
 * @license   MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @version   [0.0.1]
 * @link      http://help.infusionsoft.com/developers/services/AffiliateProgramService
 */

namespace iSDK\Services;

/**
 * AffiliateProgramService Service Class
 *
 * AffiliateProgramService [short description]
 *
 * @category Services
 * @package  AffiliateProgramService
 * @author   Elliot Boney <elliotboney@gmail.com>
 * @license  MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @link     http://help.infusionsoft.com//api-docs/affiliateprogramservice
 */
class AffiliateProgramService
{
    /**
     * Gets a list of all of the affiliates with their contact data for the specified program. This
     * includes all of the custom fields defined for the contact and affiliate records that are
     * retrieved.
     *
     * @param int $programId The Referral Partner Commission Program Id
     *
     * @return stuff
     */
    function getAffiliatesByProgram($programId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$programId));
    }

    /**
     * Gets a list of all of the Affiliate Programs for the Affiliate specified.
     *
     * @param int $affiliateId The affiliate you want to get the programs for
     *
     * @return stuff
     */
    function getProgramsForAffiliate($affiliateId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$affiliateId));
    }

    /**
     * Gets a list of all of the Affiliate Programs that are in the application.
     *
     *
     * @return stuff
     */
    function getAffiliatePrograms()
    {
        $parray = array(
);
    }

    /**
     * Gets a list of all of the resources that are associated to the Affiliate Program specified.
     *
     * @param int $programId The commission program you want the resources for
     *
     * @return stuff
     */
    function getResourcesForAffiliateProgram($programId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$programId));
    }

}
?>
