<?php
/**
 * THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
 * For more information, see http://github.com/elliotboney/
 *
 * Generated on: 04/09/2014 @ 17:54:52
 *
 * MIT License
 * ===========
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * @category  Services
 * @package   AffiliateService
 * @author    Elliot Boney <elliotboney@gmail.com>
 * @copyright 1997-2013 Digital Grove, LLC
 * @license   MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @version   [0.0.1]
 * @link      http://help.infusionsoft.com/developers/services/AffiliateService
 */

namespace iSDK\Services;

/**
 * AffiliateService Service Class
 *
 * AffiliateService [short description]
 *
 * @category Services
 * @package  AffiliateService
 * @author   Elliot Boney <elliotboney@gmail.com>
 * @license  MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @link     http://help.infusionsoft.com//api-docs/affiliateservice
 */
class AffiliateService
{
    /**
     * The affClawbacks method is used when you need to retrieve all clawed back commissions for a
     * particular affiliate. Claw backs typically occur when an order has been refunded to the
     * customer
     *
     * @param int      $affiliateId     The Id number for the affiliate record you would like the
     *                                  claw backs for
     * @param dateTime $filterStartDate The starting date for the date range which you would like
     *                                  affiliate claw backs for
     * @param dateTime $filterEndDate   The ending date for the date range which you would like the
     *                                  affiliate claw backs for
     *
     * @return stuff
     */
    function affClawbacks($affiliateId, $filterStartDate, $filterEndDate)
    {
        $parray = array(
            php_xmlrpc_encode((int)$affiliateId),
            php_xmlrpc_encode($filterStartDate, array('auto_dates')),
            php_xmlrpc_encode($filterEndDate, array('auto_dates')));
    }

    /**
     * This method is used to retrieve all commissions for a specific affiliate within a date range
     *
     * @param int      $affiliateId     The Id number for the affiliate record you would like the
     *                                  claw backs for
     * @param dateTime $filterStartDate The starting date for the date range which you would like
     *                                  affiliate commissions for
     * @param dateTime $filterEndDate   The ending date for the date range which you would like the
     *                                  affiliate commissions for
     *
     * @return stuff
     */
    function affCommissions($affiliateId, $filterStartDate, $filterEndDate)
    {
        $parray = array(
            php_xmlrpc_encode((int)$affiliateId),
            php_xmlrpc_encode($filterStartDate, array('auto_dates')),
            php_xmlrpc_encode($filterEndDate, array('auto_dates')));
    }

    /**
     * Gets a list of the Redirect Links for the specified Affiliate.
     *
     * @param int $affiliateId The Id number for the affiliate record you would like the redirect
     *                         links for
     *
     * @return stuff
     */
    function getRedirectLinksForAffiliate($affiliateId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$affiliateId));
    }

    /**
     * This method is used to retrieve all payments for a specific affiliate within a date range
     *
     * @param int      $affiliateId     The Id number for the affiliate record you would like the
     *                                  claw backs for
     * @param dateTime $filterStartDate The starting date for the date range which you would like
     *                                  affiliate payments for
     * @param dateTime $filterEndDate   The ending date for the date range which you would like the
     *                                  affiliate payments for
     *
     * @return stuff
     */
    function affPayouts($affiliateId, $filterStartDate, $filterEndDate)
    {
        $parray = array(
            php_xmlrpc_encode((int)$affiliateId),
            php_xmlrpc_encode($filterStartDate, array('auto_dates')),
            php_xmlrpc_encode($filterEndDate, array('auto_dates')));
    }

    /**
     * The affRunningTotals method is used to retrieve the current balances for Amount Earned,
     * Clawbacks, and Running Balance.
     *
     * @param array $affiliateIds An integer array of the affiliate Id numbers that you would like
     *                            the balances for
     *
     * @return stuff
     */
    function affRunningTotals($affiliateIds)
    {
        $parray = array(
            php_xmlrpc_encode($affiliateIds, array('auto_dates')));
    }

    /**
     * The affSummary method is used to retrieve a summary of statistics for a list of affiliates
     *
     * @param int      $affiliateId     An array of Affiliate Id numbers you would like stats for
     * @param dateTime $filterStartDate The starting date for the date range which you would like
     *                                  affiliate stats for
     * @param dateTime $filterEndDate   The ending date for the date range which you would like the
     *                                  affiliate stats for
     *
     * @return stuff
     */
    function affSummary($affiliateId, $filterStartDate, $filterEndDate)
    {
        $parray = array(
            php_xmlrpc_encode((int)$affiliateId),
            php_xmlrpc_encode($filterStartDate, array('auto_dates')),
            php_xmlrpc_encode($filterEndDate, array('auto_dates')));
    }

}
?>
