<?php
/**
 * THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
 * For more information, see http://github.com/elliotboney/
 *
 * Generated on: 04/09/2014 @ 15:12:50
 *
 * MIT License
 * ===========
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * @category  Services
 * @package   SearchService
 * @author    Elliot Boney <elliotboney@gmail.com>
 * @copyright 1997-2013 Digital Grove, LLC
 * @license   MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @version   [0.0.1]
 * @link      http://help.infusionsoft.com/developers/services/SearchService
 */

namespace iSDK\Services;

/**
 * SearchService Service Class
 *
 * SearchService [short description]
 *
 * @category Services
 * @package  SearchService
 * @author   Elliot Boney <elliotboney@gmail.com>
 * @license  MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @link     http://help.infusionsoft.com//api-docs/searchservice
 */
class SearchService
{
    /**
     * Gets all possible fields/columns available for return on a saved search/report
     *
     * @param int $savedSearchId The Id of the saved search you would like columns for
     * @param int $userId        The Id number of the user who created the saved search
     *
     * @return stuff
     */
    function getAllReportColumns($savedSearchId, $userId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$savedSearchId),
            php_xmlrpc_encode((int)$userId));
    }

    /**
     * Runs a saved search/report and returns all possible fields
     *
     * @param int $savedSearchId The Id number of the saved search being run
     * @param int $userId        The userId who the saved search is assigned to. If it is
     *                           &#39;Everyone&#39;, you still need to pass a valid userId
     * @param int $pageNumber    The page you would like results from. Zero is the first page
     *
     * @return stuff
     */
    function getSavedSearchResultsAllFields($savedSearchId, $userId, $pageNumber)
    {
        $parray = array(
            php_xmlrpc_encode((int)$savedSearchId),
            php_xmlrpc_encode((int)$userId),
            php_xmlrpc_encode((int)$pageNumber));
    }

    /**
     * Runs a saved search/report returning only the specified fields
     *
     * @param int   $savedSearchId The Id number of the saved search being run
     * @param int   $userId        The userId who the saved search is assigned to. If it is
     *                             &#39;Everyone&#39;, you still need to pass a valid userId
     * @param int   $pageNumber    The page you would like results from. Zero is the first page
     * @param array $returnFields  The fields/columns of data you want returned from this saved
     *                             search
     *
     * @return stuff
     */
    function getSavedSearchResults($savedSearchId, $userId, $pageNumber, $returnFields)
    {
        $parray = array(
            php_xmlrpc_encode((int)$savedSearchId),
            php_xmlrpc_encode((int)$userId),
            php_xmlrpc_encode((int)$pageNumber),
            php_xmlrpc_encode($returnFields, array('auto_dates')));
    }

    /**
     * This is used to find what possible quick searches the given user has access to
     *
     * @param int $userId The userId you are checking access for
     *
     * @return stuff
     */
    function getAvailableQuickSearches($userId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$userId));
    }

    /**
     * This allows you to run a quick search via the API. The quick search is the search bar in the
     * upper right hand corner of the Infusionsoft application
     *
     * @param int $quickSearchType The type of search you are running. Person, Order, Opportunity,
     *                             Company, Task, Subscription, or Affiliate
     * @param int $userId          The Id number of the user running this search. Results are
     *                             dependent on this users&#39; permissions
     * @param int $searchData      String to run the search based on
     * @param int $page            The page of results you would like returned
     * @param int $returnLimit     Number of results returned. Max is 1000
     *
     * @return stuff
     */
    function quickSearch($quickSearchType, $userId, $searchData, $page, $returnLimit)
    {
        $parray = array(
            php_xmlrpc_encode((int)$quickSearchType),
            php_xmlrpc_encode((int)$userId),
            php_xmlrpc_encode((int)$searchData),
            php_xmlrpc_encode((int)$page),
            php_xmlrpc_encode((int)$returnLimit));
    }

    /**
     * Retrieves the quick search type that the given users has set as their default
     *
     * @param int $userId The id of the user to lookup their search defaults
     *
     * @return stuff
     */
    function getDefaultQuickSearch($userId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$userId));
    }

}
?>
