<?php
/**
 * THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
 * For more information, see http://github.com/elliotboney/
 *
 * Generated on: 04/09/2014 @ 15:12:51
 *
 * MIT License
 * ===========
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * @category  Services
 * @package   ShippingService
 * @author    Elliot Boney <elliotboney@gmail.com>
 * @copyright 1997-2013 Digital Grove, LLC
 * @license   MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @version   [0.0.1]
 * @link      http://help.infusionsoft.com/developers/services/ShippingService
 */

namespace iSDK\Services;

/**
 * ShippingService Service Class
 *
 * ShippingService [short description]
 *
 * @category Services
 * @package  ShippingService
 * @author   Elliot Boney <elliotboney@gmail.com>
 * @license  MIT License (http://www.opensource.org/licenses/mit-license.php)
 * @link     http://help.infusionsoft.com//api-docs/shippingservice
 */
class ShippingService
{
    /**
     * Returns all shipping options configured
     *
     *
     * @return stuff
     */
    function getAllShippingOptions()
    {
        $parray = array(
);
    }

    /**
     * Returns the options and values of the flat rate shipping option provided
     *
     * @param int $optionId The Id for the shipping option
     *
     * @return stuff
     */
    function getFlatRateShippingOption($optionId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$optionId));
    }

    /**
     * Returns the options and values of the order total shipping option provided
     *
     * @param int $optionId The Id for the shipping option
     *
     * @return stuff
     */
    function getOrderTotalShippingOption($optionId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$optionId));
    }

    /**
     * Returns the options and values of the order total shipping ranges option provided
     *
     * @param int $optionId The Id for the shipping option
     *
     * @return stuff
     */
    function getOrderTotalShippingRanges($optionId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$optionId));
    }

    /**
     * Returns the options and values of the product based shipping option provided
     *
     * @param int $optionId The Id for the shipping option
     *
     * @return stuff
     */
    function getProductBasedShippingOption($optionId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$optionId));
    }

    /**
     * Returns the options and values of the order quantity shipping option provided
     *
     * @param int $optionId The Id for the shipping option
     *
     * @return stuff
     */
    function getOrderQuantityShippingOption($optionId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$optionId));
    }

    /**
     * Returns the options and values of the weight based shipping option provided
     *
     * @param int $optionId The Id for the shipping option
     *
     * @return stuff
     */
    function getWeightBasedShippingOption($optionId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$optionId));
    }

    /**
     * Returns the options and values of the ups shipping option provided
     *
     * @param int $optionId The Id for the shipping option
     *
     * @return stuff
     */
    function getUpsShippingOption($optionId)
    {
        $parray = array(
            php_xmlrpc_encode((int)$optionId));
    }

}
?>
